apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-mock-data-config
  namespace: ${config_file}
data:
  custom.yml: |
    data:
      amounts:
        flavors: 500
        service_instances: 500     # belongs_to [:source_region, :service_offering, :service_plan]
        service_offerings: 1000    # belongs_to [:source_region]
        service_offering_icons: 500
        service_offering_tags: 1000
        service_plans: 1500        # belongs_to [:source_region, :service_offering]
        source_regions: 500
        volumes: 1000              # belongs_to [:volume_type, :source_region]
        volume_attachments: 10
        volume_types: 500
        vms: 1000                  # belongs_to [:flavor]
        vm_tags: 5000